export const mockSalaryData = [
  {
    _id: "36 萬以下",
    count: 14,
    industry: [
      { _id: "接案公司", count: 7 },
      { _id: "博奕", count: 0 },
      { _id: "電子商務", count: 1 },
      { _id: "SaaS 服務", count: 0 },
      { _id: "數位整合行銷", count: 3 },
      { _id: "金融相關 (銀行、保險)", count: 0 },
      { _id: "其他產業", count: 3 },
    ],
  },
  {
    _id: "36~50 萬",
    count: 117,
    industry: [
      { _id: "接案公司", count: 38 },
      { _id: "博奕", count: 13 },
      { _id: "電子商務", count: 9 },
      { _id: "SaaS 服務", count: 5 },
      { _id: "數位整合行銷", count: 8 },
      { _id: "金融相關 (銀行、保險)", count: 2 },
      { _id: "其他產業", count: 42 },
    ],
  },
  {
    _id: "51~60 萬",
    count: 96,
    industry: [
      { _id: "接案公司", count: 25 },
      { _id: "博奕", count: 16 },
      { _id: "電子商務", count: 11 },
      { _id: "SaaS 服務", count: 11 },
      { _id: "數位整合行銷", count: 3 },
      { _id: "金融相關 (銀行、保險)", count: 5 },
      { _id: "其他產業", count: 25 },
    ],
  },
  {
    _id: "61~70 萬",
    count: 76,
    industry: [
      { _id: "接案公司", count: 12 },
      { _id: "博奕", count: 5 },
      { _id: "電子商務", count: 10 },
      { _id: "SaaS 服務", count: 3 },
      { _id: "數位整合行銷", count: 8 },
      { _id: "金融相關 (銀行、保險)", count: 2 },
      { _id: "其他產業", count: 36 },
    ],
  },
  {
    _id: "71~80 萬",
    count: 55,
    industry: [
      { _id: "接案公司", count: 4 },
      { _id: "博奕", count: 8 },
      { _id: "電子商務", count: 13 },
      { _id: "SaaS 服務", count: 11 },
      { _id: "數位整合行銷", count: 4 },
      { _id: "金融相關 (銀行、保險)", count: 2 },
      { _id: "其他產業", count: 13 },
    ],
  },
  {
    _id: "81~90 萬",
    count: 36,
    industry: [
      { _id: "接案公司", count: 4 },
      { _id: "博奕", count: 6 },
      { _id: "電子商務", count: 6 },
      { _id: "SaaS 服務", count: 3 },
      { _id: "數位整合行銷", count: 1 },
      { _id: "金融相關 (銀行、保險)", count: 7 },
      { _id: "其他產業", count: 9 },
    ],
  },
  {
    _id: "91~100 萬",
    count: 30,
    industry: [
      { _id: "接案公司", count: 3 },
      { _id: "博奕", count: 6 },
      { _id: "電子商務", count: 3 },
      { _id: "SaaS 服務", count: 3 },
      { _id: "數位整合行銷", count: 3 },
      { _id: "金融相關 (銀行、保險)", count: 0 },
      { _id: "其他產業", count: 12 },
    ],
  },
  {
    _id: "101~110 萬",
    count: 21,
    industry: [
      { _id: "接案公司", count: 2 },
      { _id: "博奕", count: 2 },
      { _id: "電子商務", count: 1 },
      { _id: "SaaS 服務", count: 3 },
      { _id: "數位整合行銷", count: 3 },
      { _id: "金融相關 (銀行、保險)", count: 0 },
      { _id: "其他產業", count: 10 },
    ],
  },
  {
    _id: "111~120 萬",
    count: 12,
    industry: [
      { _id: "接案公司", count: 0 },
      { _id: "博奕", count: 4 },
      { _id: "電子商務", count: 1 },
      { _id: "SaaS 服務", count: 2 },
      { _id: "數位整合行銷", count: 0 },
      { _id: "金融相關 (銀行、保險)", count: 0 },
      { _id: "其他產業", count: 5 },
    ],
  },
  {
    _id: "120 萬以上",
    count: 24,
    industry: [
      { _id: "接案公司", count: 1 },
      { _id: "博奕", count: 5 },
      { _id: "電子商務", count: 3 },
      { _id: "SaaS 服務", count: 4 },
      { _id: "數位整合行銷", count: 1 },
      { _id: "金融相關 (銀行、保險)", count: 2 },
      { _id: "其他產業", count: 8 },
    ],
  },
];
